/* This file was generated by the "svnrev" utility.
 * You should not modify it manually, as it may be re-generated.
 *
 */

#ifndef SVNREV_H
#define SVNREV_H

#define SVN_REV     "release 2.2"
#define SVN_REVDATE "Unknown"
#define BUILD_DATE "Mon Nov 20 18:30:01 EST 2017"

#endif /* SVNREV_H */


